// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yV1SFQL_Mjlzbp3TsnN9J0TvEPK2MQA',
    appId: '1:1089050438573:web:0c942041d8c29d2e180f24',
    messagingSenderId: '1089050438573',
    projectId: 'qubi-app-dev',
    authDomain: 'qubi-app-dev.firebaseapp.com',
    storageBucket: 'qubi-app-dev.firebasestorage.app',
    measurementId: 'G-7GFT86GHVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNC-YQ14Seej11FBD-mqifOYU5WPkOvw',
    appId: '1:1089050438573:android:193dec3d9a44b1fc180f24',
    messagingSenderId: '1089050438573',
    projectId: 'qubi-app-dev',
    storageBucket: 'qubi-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhAH55q901QflDlzhbIfR0SK90Z41Fqs',
    appId: '1:1089050438573:ios:61d54b4ba4750e9d180f24',
    messagingSenderId: '1089050438573',
    projectId: 'qubi-app-dev',
    storageBucket: 'qubi-app-dev.firebasestorage.app',
    androidClientId: '1089050438573-3q346kjfuu7mh20al7q3ot090v8p9qco.apps.googleusercontent.com',
    iosClientId: '1089050438573-6s9rr4vt3g43uoge8p0m94kqbridk09q.apps.googleusercontent.com',
    iosBundleId: 'com.example.qubiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhAH55q901QflDlzhbIfR0SK90Z41Fqs',
    appId: '1:1089050438573:ios:61d54b4ba4750e9d180f24',
    messagingSenderId: '1089050438573',
    projectId: 'qubi-app-dev',
    storageBucket: 'qubi-app-dev.firebasestorage.app',
    androidClientId: '1089050438573-3q346kjfuu7mh20al7q3ot090v8p9qco.apps.googleusercontent.com',
    iosClientId: '1089050438573-6s9rr4vt3g43uoge8p0m94kqbridk09q.apps.googleusercontent.com',
    iosBundleId: 'com.example.qubiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yV1SFQL_Mjlzbp3TsnN9J0TvEPK2MQA',
    appId: '1:1089050438573:web:33eb5cf2a4e7289a180f24',
    messagingSenderId: '1089050438573',
    projectId: 'qubi-app-dev',
    authDomain: 'qubi-app-dev.firebaseapp.com',
    storageBucket: 'qubi-app-dev.firebasestorage.app',
    measurementId: 'G-PDBMYMGZ6T',
  );

}